price = input("What is the price of a child's meal? ")
print()
price = input("What is the price of an adult's meal? ")
print()
total = input("How many children are there? ")
print()
total = input("How many adults are there? ")
print()
total = input("What is the sales tax rate? ")
print()
money = input("What is the payment amount? ")
print()
print()